version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: pg-dbt
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pg_dbt_data:/var/lib/postgresql/data

volumes:
  pg_dbt_data:
